package com.axiomalaska.ioos.sos.validator.provider;

public enum SosDocumentType {
    M1_0_CAPABILITIES,
    M1_0_SENSOR_ML_NETWORK,
    M1_0_SENSOR_ML_STATION,
    M1_0_SENSOR_ML_SENSOR,
    M1_0_OBSERVATION_COLLECTION_TIME_SERIES,
    M1_0_OBSERVATION_COLLECTION_TIME_SERIES_PROFILE
}